### ISSUE TITLE
TypeError: undefined is not an object (evaluating '$scope.index.arrBalances.length')

### ISSUE THREAD

**Issue by dagcoin1** [dagcoin/dagcoin#1304]
https://sentry.io/dagcoin/dagcoin/issues/557539296/

```
TypeError: undefined is not an object (evaluating '$scope.index.arrBalances.length')
  at canSendExternalPayment (/dagcoin.js:230398:35)
  at expressionInputWatch (/angular.js:30330:47)
  at $digest (/angular.js:31846:43)
  at $apply (/angular.js:32125:31)
  at None (/angular.js:33892:42)
...
(3 additional frame(s) were not displayed)
```

**Comment by dagcoin1** [comment]
Sentry issue: [DAGCOIN-TA](https://sentry.io/dagcoin/dagcoin/issues/556192751/)

**Comment by dagcoin1** [comment]
Sentry issue: [DAGCOIN-ZB](https://sentry.io/dagcoin/dagcoin/issues/559041747/)

**Comment by dagcoin1** [comment]
Sentry issue: [DAGCOIN-ZA](https://sentry.io/dagcoin/dagcoin/issues/559041746/)

**Comment by dagcoin1** [comment]
Sentry issue: [DAGCOIN-TE](https://sentry.io/dagcoin/dagcoin/issues/556193263/)

**Comment by dagcoin1** [comment]
Sentry issue: [DAGCOIN-XG](https://sentry.io/dagcoin/dagcoin/issues/557684767/)

**Comment by dagcoin1** [comment]
Sentry issue: [DAGCOIN-WE](https://sentry.io/dagcoin/dagcoin/issues/557241260/)
