### ISSUE TITLE
An e xception occurred: TypeError: Cannot read property 'pub_b64' of undefined; cause: <section u...

### ISSUE THREAD

**Issue by dagcoin1** [dagcoin/dagcoin#1310]
https://sentry.io/dagcoin/dagcoin/issues/554462848/

```
Stacktrace (most recent call first):

  at EventEmitter.<anonymous> (/android_asset/www/dagcoin.js:153261:13)
  at EventEmitter.emit (/android_asset/www/dagcoin.js:81015:20)
  at exHandler (/android_asset/www/dagcoin.js:149894:16)
  at None (/android_asset/www/angular.js:71509:7)
  at invokeLinkFn (/android_asset/www/angular.js:24877:9)
  at nodeLinkFn (/android_asset/www/angular.js:24375:11)
  at compositeLinkFn (/android_asset/www/angular.js:23766:13)
  at publicLinkFn (/android_asset/www/angular.js:23641:30)
  at updateView (/android_asset/www/angular.js:48885:23)
  at None (/android_asset/www/angular.js:48847:11)
...
(13 additional frame(s) were not displayed)

An e xception occurred: TypeError: Cannot read property 'pub_b64' of undefined; cause: <section ui-view="main" class="section {{viewTransition}} ng-scope" ng-class="{'main': index.hasProfile, 'has-notification': pass.walletInfoVisibility.visible &amp;&amp; index.needsBackup}" data-ng-animate="1">
```

**Comment by dagcoin1** [comment]
Sentry issue: [DAGCOIN-G5](https://sentry.io/dagcoin/dagcoin/issues/504072724/)

**Comment by msinansahin** [comment]
I think, the error occurs when device.startWaitingForPairing method is being called. It is calle somehow when objMyPermanentDeviceKey global variable not set.
