### ISSUE TITLE
TypeError: Cannot read property 'shareViaEmail' of undefined

### ISSUE THREAD

**Issue by dagcoin1** [dagcoin/dagcoin#1313]
https://sentry.io/dagcoin/dagcoin/issues/556017617/

```
TypeError: Cannot read property 'shareViaEmail' of undefined
  at None (/dagcoin.js:227915:40)
  at None (/dagcoin.js:524:5)
  at None (/dagcoin.js:147664:7)
  at None (/dagcoin.js:140579:9)
  at None (/dagcoin.js:140472:11)
...
(2 additional frame(s) were not displayed)
```

**Comment by fishera123** [comment]
fixed in issue-1313
