### ISSUE TITLE
An e xception occurred: Error: [$compile:tpload] Failed to load template: views/includes/notifica...

### ISSUE THREAD

**Issue by dagcoin1** [dagcoin/dagcoin#485]
https://sentry.io/dagcoin/dagcoin/issues/364005276/

```
Stacktrace (most recent call first):

  at EventEmitter.<anonymous> (/android_asset/www/dagcoin.js:153469:286)
  at EventEmitter.emit (/android_asset/www/dagcoin.js:84613:17)
  at exHandler (/android_asset/www/dagcoin.js:153159:338)
  at None (/android_asset/www/angular.js:73216:13)
  at processQueue (/android_asset/www/angular.js:30778:9)
  at None (/android_asset/www/angular.js:30786:27)
  at Scope.$eval (/android_asset/www/angular.js:32014:28)
  at Scope.$digest (/android_asset/www/angular.js:31825:31)
  at Scope.$apply (/android_asset/www/angular.js:32122:24)
  at done (/android_asset/www/angular.js:26637:47)
...
(5 additional frame(s) were not displayed)

An e xception occurred: Error: [$compile:tpload] Failed to load template: views/includes/notifications.html (HTTP status: -1 )
http://errors.angularjs.org/1.4.6/$compile/tpload?p0=views%2Fincludes%2Fnotifications.html&p1=-1&p2=; cause: undefined
```

**Comment by irinadoros** [comment]
Fixed.
